package com.sdc.ast;


public enum OperationType {
    ADD, SUB, MUL, DIV, REM,
    INC, DEC, INC_REV, DEC_REV, ADD_INC, SUB_INC, MUL_INC, DIV_INC, REM_INC,
    AND, OR, BITWISE_AND, BITWISE_OR, BITWISE_XOR, EQ, NE, GE, GT, LE, LT, SHR, SHL, USHR,
    NOT, NEGATE, DOUBLE_CAST, INT_CAST, LONG_CAST, SHORT_CAST, BYTE_CAST, CHAR_CAST, FLOAT_CAST, TERNARY_IF,
    ARRAYLENGTH, NEWARRAY, SQUARE_BRACKETS, VARIABLE, FIELD, CHECK_CAST, INVOCATION, NEW, INSTANCEOF, CONST

}
